#!/usr/bin/env bash
set -uo pipefail

# Runs the project's test suites and always writes a timestamped summary to
# docs/human/test-runs/latest.md — pass or fail. This is deliberately NOT the
# coverage report (see coverage.command / generate_coverage_metrics.py): no
# bytecode instrumentation, no HTML, no trend history — just "what ran, did it
# pass, how long did it take, how many tests." Cheap enough to run on every
# scheduled sweep without slowing it down, and gives a glanceable artifact
# without waiting for a failure to notice something ran at all.
#
# Suites:
#   1. Unit tests        (./gradlew :composeApp:testDebugUnitTest) — always runs.
#   2. Instrumented tests (connectedDebugAndroidTest) — only if a booted Android
#      emulator is detected via `adb devices`; skipped (not failed) otherwise.
#
# Usage: ./run-full-tests.sh

cd "$(dirname "${BASH_SOURCE[0]}")"

OUT_DIR="docs/human/test-runs"
OUT_FILE="$OUT_DIR/latest.md"
mkdir -p "$OUT_DIR"

TIMESTAMP="$(date +"%Y-%m-%d %H:%M:%S %z")"

# --- helpers -----------------------------------------------------------

# Sums tests/failures/skipped attributes across a directory of JUnit XML
# reports. Prints "tests failures skipped" (space-separated) or "0 0 0" if
# no reports are found. Deliberately grep/sed-based, not XML-parsed — this
# script has zero new dependencies (no python, no jq) on purpose.
sum_junit_xml() {
  local dir="$1"
  local tests=0 failures=0 skipped=0
  if [ -d "$dir" ]; then
    while IFS= read -r f; do
      local t f_ s
      t=$(grep -o 'tests="[0-9]*"' "$f" | head -1 | grep -o '[0-9]*' || echo 0)
      f_=$(grep -o 'failures="[0-9]*"' "$f" | head -1 | grep -o '[0-9]*' || echo 0)
      s=$(grep -o 'skipped="[0-9]*"' "$f" | head -1 | grep -o '[0-9]*' || echo 0)
      tests=$((tests + ${t:-0}))
      failures=$((failures + ${f_:-0}))
      skipped=$((skipped + ${s:-0}))
    done < <(find "$dir" -name '*.xml' 2>/dev/null)
  fi
  echo "$tests $failures $skipped"
}

format_duration() {
  local secs=$1
  printf "%dm%02ds" $((secs / 60)) $((secs % 60))
}

# Resolve adb without fully trusting PATH — some shells (including the one this
# script has been run from during development) carry an unexpanded
# "~/Library/Android/sdk/platform-tools" entry, which silently fails to
# resolve `adb` via `command -v` even when it's actually installed there. Fall
# back to the common install locations before giving up.
resolve_adb() {
  if command -v adb >/dev/null 2>&1; then
    command -v adb
    return
  fi
  local candidates=(
    "${ANDROID_HOME:-}/platform-tools/adb"
    "${ANDROID_SDK_ROOT:-}/platform-tools/adb"
    "$HOME/Library/Android/sdk/platform-tools/adb"
  )
  for c in "${candidates[@]}"; do
    if [ -n "$c" ] && [ -x "$c" ]; then
      echo "$c"
      return
    fi
  done
}

# --- suite 1: unit tests (always runs) ----------------------------------

echo "Running unit tests..."
UNIT_START=$(date +%s)
if ./gradlew :composeApp:testDebugUnitTest -PincludeAllTargets=false --no-daemon --stacktrace; then
  UNIT_RESULT="PASS"
else
  UNIT_RESULT="FAIL"
fi
UNIT_END=$(date +%s)
UNIT_DURATION=$(format_duration $((UNIT_END - UNIT_START)))
read -r UNIT_TESTS UNIT_FAILURES UNIT_SKIPPED <<< "$(sum_junit_xml "composeApp/build/test-results/testDebugUnitTest")"

# --- suite 2: instrumented tests (only if an emulator is present) -------

INSTRUMENTED_STATUS="SKIPPED (no emulator detected)"
INSTRUMENTED_TESTS="—"
INSTRUMENTED_FAILURES="—"
INSTRUMENTED_DURATION="—"

ADB_BIN="$(resolve_adb)"

if [ -n "$ADB_BIN" ] && "$ADB_BIN" devices 2>/dev/null | grep -qE '\bdevice$'; then
  echo "Emulator detected (adb: $ADB_BIN) — running instrumented tests..."
  INSTR_START=$(date +%s)
  if ./gradlew :composeApp:connectedDebugAndroidTest -PincludeAllTargets=false --no-daemon --stacktrace; then
    INSTRUMENTED_STATUS="PASS"
  else
    INSTRUMENTED_STATUS="FAIL"
  fi
  INSTR_END=$(date +%s)
  INSTRUMENTED_DURATION=$(format_duration $((INSTR_END - INSTR_START)))
  read -r INSTRUMENTED_TESTS INSTRUMENTED_FAILURES _ <<< "$(sum_junit_xml "composeApp/build/outputs/androidTest-results/connected")"
else
  if [ -z "$ADB_BIN" ]; then
    echo "adb not found (checked PATH, \$ANDROID_HOME, \$ANDROID_SDK_ROOT, ~/Library/Android/sdk) — skipping instrumented tests."
  else
    echo "No booted emulator (adb devices found none) — skipping instrumented tests."
  fi
fi

# --- write the summary (always, pass or fail) ---------------------------

{
  echo "# Test run — $TIMESTAMP"
  echo
  echo "| Suite | Result | Tests | Failures | Duration |"
  echo "|---|---|---|---|---|"
  echo "| Unit tests (\`testDebugUnitTest\`) | $UNIT_RESULT | $UNIT_TESTS | $UNIT_FAILURES | $UNIT_DURATION |"
  echo "| Instrumented (\`connectedDebugAndroidTest\`) | $INSTRUMENTED_STATUS | $INSTRUMENTED_TESTS | $INSTRUMENTED_FAILURES | $INSTRUMENTED_DURATION |"
  echo
  echo "_Generated by \`run-full-tests.sh\`. This file is overwritten on every run — it's a_"
  echo "_glance-at-it artifact, not a history log (see \`docs/coverage/history.json\` for the_"
  echo "_coverage trend equivalent, which is a separate, opt-in, heavier report)._"
} > "$OUT_FILE"

echo
echo "Summary written to $OUT_FILE"

if [ "$UNIT_RESULT" = "FAIL" ] || [ "$INSTRUMENTED_STATUS" = "FAIL" ]; then
  exit 1
fi
exit 0
