package core

/**
 * Data class holding all app strings for a given language.
 * Plurals are represented as lambdas that take a count parameter.
 *
 * Property names use camelCase. String format parameters are handled by the calling site.
 * Lambdas that take string parameters use typed arguments.
 */
data class AppStrings(
    // Common / Shared
    val ok: String,
    val cancel: String,
    /** Generic "Done" confirm-and-close label (e.g. after a successful key save). */
    val done: String,
    val delete: String,
    val back: String,
    val save: String,
    val downloading: String,
    val previousMonth: String,
    val nextMonth: String,
    val appTitle: String,
    val dismiss: String,
    val download: String,

    // HomeView
    val savedLocations: String,
    val searchPlaceholder: String,
    val apiError: String,
    val deletePlaceTitle: String,
    val deletePlaceMessage: (String) -> String,
    val settingsIconDesc: String,
    val chatIconDesc: String,
    val daysStored: (Int) -> String,
    val vcKeyNudgeTitle: String,
    val vcKeyNudgeBody: String,
    val vcKeyNudgeAction: String,
    // Claude (Anthropic) first-run key nudge — shown in Chat until a key is stored (KIM-252).
    val claudeKeyNudgeTitle: String,
    val claudeKeyNudgeBody: String,
    val claudeKeyNudgeAction: String,

    // ChatView
    val chatTitle: String,
    val messagePlaceholder: String,
    val sendMessageDesc: String,
    // Chat session switcher (KIM-286)
    val sessionSwitcherIconDesc: String,
    val sessionSwitcherTitle: String,
    val sessionSwitcherNewChat: String,
    val sessionSwitcherEmpty: String,
    val sessionSwitcherClose: String,
    val sessionSwitcherActiveDesc: String,
    val sessionMessageCount: (Long) -> String,
    val apiKeyNotConfigured: String,
    val apiKeyNotConfiguredMessage: String,
    val warningIconDesc: String,
    val goToSettings: String,
    val claudeKeyInvalidTitle: String,
    val claudeKeyInvalidMessage: String,
    val vcKeyMissingTitle: String,
    val vcKeyMissingMessage: String,
    val vcKeyInvalidTitle: String,
    val vcKeyInvalidMessage: String,

    // SettingsView
    val settingsTitle: String,
    val languageTitle: String,
    val anthropicKeyTitle: String,
    val anthropicKeyDescription: String,
    val apiKeyConfigured: String,
    val apiKeyNotConfiguredStatus: String,
    val apiKeySaved: String,
    /** Inline validation shown when the user tries to save a blank key field (KIM-252). */
    val apiKeyEmptyError: String,
    val apiKeyPlaceholder: String,
    val apiKeyFieldLabel: String,
    /** Lead-in text before the tappable "get an API key" link (KIM-252). */
    val anthropicApiUrl: String,
    /** Tappable link label opening the Anthropic console in the system browser (KIM-252). */
    val anthropicApiLinkLabel: String,
    val saveKey: String,
    val visualCrossingKeyTitle: String,
    val visualCrossingKeyDescription: String,
    val visualCrossingApiUrl: String,
    val deleteKeyTitle: (String) -> String,
    val deleteKeyMessage: (String) -> String,

    // SettingsView — grouped list (KIM-273)
    val settingsGroupGeneral: String,
    val settingsGroupApiKeys: String,
    val settingsGroupData: String,
    val settingsGroupAbout: String,
    val settingsRowUnits: String,
    val settingsRowWindSpeed: String,
    val settingsRowAutoRefresh: String,
    val settingsRowWifiOnly: String,
    val settingsRowExportData: String,
    val settingsRowVersion: String,
    val settingsRowDeleteAllData: String,
    val settingsKeyConfiguredChip: String,
    val settingsKeyNotSetChip: String,
    val settingsAnthropicSubLabel: String,
    val settingsVisualCrossingSubLabel: String,
    val settingsAppVersion: String,
    // About group — welcome guide + feedback (KIM-334)
    val settingsRowWhatIsReWinds: String,
    val settingsRowSendFeedback: String,

    // Welcome / onboarding guide (KIM-334)
    val welcomeTitle: String,
    val welcomeWhatItIsHeading: String,
    val welcomeWhatItIsBody: String,
    val welcomeWhatItIsNotHeading: String,
    val welcomeWhatItIsNotBody: String,
    val welcomeGetStarted: String,
    val welcomeDone: String,

    // Feedback email (KIM-334)
    val feedbackEmailSubject: String,
    /** Body prefix; caller appends "App version: … / Platform: …" diagnostics. */
    val feedbackEmailBodyIntro: String,

    // StationMapModal
    val noStationData: String,
    val refreshStations: String,
    val refreshStationsDesc: String,
    val unknownStation: String,
    val stationRefreshError: (String) -> String,
    val closeMap: String,
    val mapStationIconDesc: String,
    // Sheet subtitle, e.g. "3 weather stations · closest 2.3 km"
    val mapSheetSubtitle: (Int, String) -> String,
    val mapSheetSubtitleNoDistance: (Int) -> String,
    // Info panel primary line, e.g. "3 weather stations nearby"
    val stationsNearby: (Int) -> String,
    // Info panel secondary line, e.g. "Closest station 2.3 km away"
    val closestStationAway: (String) -> String,
    val noStationsNearby: String,

    // PlaceSummaryView
    val infoIconDesc: String,
    val openMapButton: String,
    val chatButton: String,
    val monthPartialLabel: String,
    val monthDownloadedLabel: String,
    val downloadFullMonth: String,
    val loadingSummary: String,
    val errorLabel: String,
    val noStoredDays: String,
    val daysFraction: (Int, Int) -> String,
    val tempDisplay: (String) -> String,
    val missingDaysMessage: (String, Int, Int) -> String,
    val notDownloadedMessage: (String, Int) -> String,

    // Month Names - Short
    val monthShortJan: String,
    val monthShortFeb: String,
    val monthShortMar: String,
    val monthShortApr: String,
    val monthShortMay: String,
    val monthShortJun: String,
    val monthShortJul: String,
    val monthShortAug: String,
    val monthShortSep: String,
    val monthShortOct: String,
    val monthShortNov: String,
    val monthShortDec: String,

    // Month Names - Full
    val monthJanuary: String,
    val monthFebruary: String,
    val monthMarch: String,
    val monthApril: String,
    val monthMay: String,
    val monthJune: String,
    val monthJuly: String,
    val monthAugust: String,
    val monthSeptember: String,
    val monthOctober: String,
    val monthNovember: String,
    val monthDecember: String,

    // MonthlyStatisticsView
    val monthlySummary: String,
    val daysOfInterest: (Int) -> String,
    val generalStats: String,
    val dailyBreakdown: String,
    val daysWithData: (String) -> String,
    val avgMinTemp: (String) -> String,
    val avgMaxTemp: (String) -> String,
    val overallAvgTemp: (String) -> String,
    val coldestDay: (String, String) -> String,
    val hottestDay: (String, String) -> String,
    val totalSolarEnergy: (String) -> String,
    val totalRainfall: (String) -> String,
    val noWeatherData: String,
    val downloadMissingDays: (Int) -> String,
    val daysRecorded: (Int) -> String,
    val statTempLabel: String,
    val statTempValue: (String, String) -> String,
    val statWindLabel: String,
    val statRainfallLabel: String,
    val statKiteableDaysLabel: String,
    val unitCelsius: String,
    val unitKmh: String,
    val unitMm: String,
    val unitDays: String,
    val dailyWind: String,

    // WeatherCards
    val maxTemp: String,
    val avgTemp: String,
    val minTemp: String,
    val avgWind: String,
    val sustWind: String,
    val maxWind: String,
    val noDate: String,

    // DaySummaryRow
    // Caption qualifying the collapsed-row wind figure as a sustained (2h rolling-average)
    // reading rather than a peak gust (KIM-354).
    val dayWindBestWindowLabel: String,
    val noDetails: String,
    val solarEnergy: (String) -> String,
    val lowVisibilityDesc: String,
    val lowVisibilityHours: (Int) -> String,
    val collapse: String,
    val expand: String,
    val dayMinTemp: (String) -> String,
    val dayMaxTemp: (String) -> String,
    val dayWindDirection: (String) -> String,
    val dayRainfall: (String) -> String,
    val daySunrise: (String) -> String,
    val daySunset: (String) -> String,

    // DayDetailSheet (hourly wind chart)
    val hourlyWindSpeedLegend: String,
    val hourlyWindGustLegend: String,
    val hourlySustainedWindowLegend: String,
    val hourlyMeetsThresholdLegend: String,
    val noHourlyData: String,
    val hourlyWindChartDesc: (String, String, String, String) -> String,
    val windDirectionDesc: (String) -> String,

    // CalendarSelectors
    val selectYear: String,
    val selectMonth: String,
    val noDataAvailable: String,
    val monthFallbackNa: String,
    val monthFallbackNumber: (Int) -> String,

    // Days of Interest (SettingsView)
    val daysOfInterestTitle: String,
    val daysOfInterestDescription: String,
    val daysOfInterestPlaceholder: String,
    val daysOfInterestCurrent: (String) -> String,
    val daysOfInterestParsing: String,
    val daysOfInterestSave: String,
    val daysOfInterestError: (String) -> String
) {
    companion object {
        val English = AppStrings(
            // Common / Shared
            ok = "OK",
            cancel = "Cancel",
            done = "Done",
            delete = "Delete",
            back = "Back",
            save = "Save",
            downloading = "Downloading...",
            previousMonth = "Previous month",
            nextMonth = "Next month",
            appTitle = "ReWinds",
            dismiss = "Dismiss",
            download = "Download",

            // HomeView
            savedLocations = "Saved Locations",
            searchPlaceholder = "Search for new locations...",
            apiError = "API Error",
            deletePlaceTitle = "Delete Place",
            deletePlaceMessage = { name -> "Are you sure you want to delete '$name'? This action cannot be undone." },
            settingsIconDesc = "Settings",
            chatIconDesc = "AI Chat",
            daysStored = { count -> if (count == 1) "$count day stored data" else "$count days stored data" },
            vcKeyNudgeTitle = "Weather data not set up",
            vcKeyNudgeBody = "ReWinds uses Visual Crossing as its weather data source. Add your API key to start downloading weather data.",
            vcKeyNudgeAction = "Set up now",
            claudeKeyNudgeTitle = "AI chat not set up",
            claudeKeyNudgeBody = "AI chat uses Claude by Anthropic. Add your Anthropic API key to start chatting.",
            claudeKeyNudgeAction = "Set up now",

            // ChatView
            chatTitle = "Chat",
            messagePlaceholder = "Type your message...",
            sendMessageDesc = "Send message",
            sessionSwitcherIconDesc = "Chat history",
            sessionSwitcherTitle = "Your chats",
            sessionSwitcherNewChat = "New chat",
            sessionSwitcherEmpty = "No saved chats yet. Start a new one to begin.",
            sessionSwitcherClose = "Close chat list",
            sessionSwitcherActiveDesc = "Current chat",
            sessionMessageCount = { count -> if (count == 1L) "$count message" else "$count messages" },
            apiKeyNotConfigured = "API Key Not Configured",
            apiKeyNotConfiguredMessage = "To use AI chat, add your Anthropic API key in Settings. You can get a key from the Anthropic console.",
            warningIconDesc = "Warning",
            goToSettings = "Go to Settings",
            claudeKeyInvalidTitle = "Claude API Key Invalid",
            claudeKeyInvalidMessage = "Your Anthropic API key was rejected (401/403). Please check your key in Settings.",
            vcKeyMissingTitle = "Weather API Key Not Configured",
            vcKeyMissingMessage = "A Visual Crossing API key is required to download weather data. Add your key in Settings.",
            vcKeyInvalidTitle = "Weather API Key Invalid",
            vcKeyInvalidMessage = "Your Visual Crossing API key was rejected (401/403). Please check your key in Settings.",

            // SettingsView
            settingsTitle = "Settings",
            languageTitle = "Language",
            anthropicKeyTitle = "Anthropic API Key",
            anthropicKeyDescription = "Enter your Anthropic API key to use AI chat. Your key is stored securely on your device.",
            apiKeyConfigured = "\u2713 API key is configured",
            apiKeyNotConfiguredStatus = "\u26A0 API key not configured",
            apiKeySaved = "\u2713 API key saved",
            apiKeyEmptyError = "Please enter your API key.",
            apiKeyPlaceholder = "sk-ant-...",
            apiKeyFieldLabel = "API Key",
            anthropicApiUrl = "Don't have a key yet?",
            anthropicApiLinkLabel = "Get an API key from the Anthropic console",
            saveKey = "Save Key",
            visualCrossingKeyTitle = "Visual Crossing API Key",
            visualCrossingKeyDescription = "Visual Crossing provides the historical and forecast weather data that powers ReWinds. You can create a free account with no credit card required. The free tier allows 1,000 records per day, which is plenty for personal use. Your key is stored securely on your device.",
            visualCrossingApiUrl = "Create a free account at: https://www.visualcrossing.com/weather-api",
            deleteKeyTitle = { keyType -> "Delete $keyType?" },
            deleteKeyMessage = { keyType -> "This will remove your stored $keyType. You can add it again later from settings." },

            // SettingsView — grouped list (KIM-273)
            settingsGroupGeneral = "General",
            settingsGroupApiKeys = "API Keys",
            settingsGroupData = "Data",
            settingsGroupAbout = "About",
            settingsRowUnits = "Units",
            settingsRowWindSpeed = "Wind speed",
            settingsRowAutoRefresh = "Auto-refresh",
            settingsRowWifiOnly = "Refresh on Wi-Fi only",
            settingsRowExportData = "Export data",
            settingsRowVersion = "Version",
            settingsRowDeleteAllData = "Delete all data",
            settingsKeyConfiguredChip = "✓ Configured",
            settingsKeyNotSetChip = "Not set",
            settingsAnthropicSubLabel = "AI chat feature",
            settingsVisualCrossingSubLabel = "Weather data",
            settingsAppVersion = "1.0.0",
            settingsRowWhatIsReWinds = "What is ReWinds?",
            settingsRowSendFeedback = "Send feedback",

            // Welcome / onboarding guide (KIM-334)
            welcomeTitle = "Welcome to ReWinds",
            welcomeWhatItIsHeading = "What it's for",
            welcomeWhatItIsBody = "ReWinds helps wind sports enthusiasts find great spots. Search a location and explore its historical wind and weather patterns — sustained wind, gusts, and monthly stats — to plan trips and chase the wind.",
            welcomeWhatItIsNotHeading = "What it's not",
            welcomeWhatItIsNotBody = "It's not a live forecast app. ReWinds won't tell you tomorrow's weather — it shows the historical patterns that reveal where and when the wind tends to blow.",
            welcomeGetStarted = "Get Started",
            welcomeDone = "Done",

            // Feedback email (KIM-334)
            feedbackEmailSubject = "ReWinds Feedback",
            feedbackEmailBodyIntro = "Tell us what you think:",

            // StationMapModal
            noStationData = "No station data available",
            refreshStations = "Refresh stations",
            refreshStationsDesc = "Refresh weather station data",
            unknownStation = "Unknown station",
            stationRefreshError = { msg -> "Station refresh failed: $msg" },
            closeMap = "Close map",
            mapStationIconDesc = "Weather stations",
            mapSheetSubtitle = { count, km -> "$count weather stations · closest $km km" },
            mapSheetSubtitleNoDistance = { count -> "$count weather stations" },
            stationsNearby = { count -> "$count weather stations nearby" },
            closestStationAway = { km -> "Closest station $km km away" },
            noStationsNearby = "No weather stations nearby",

            // PlaceSummaryView
            infoIconDesc = "Info",
            openMapButton = "Open station map",
            chatButton = "Chat",
            monthPartialLabel = "Partial",
            monthDownloadedLabel = "Downloaded",
            downloadFullMonth = "Download full month?",
            loadingSummary = "Loading weather summary...",
            errorLabel = "Error:",
            noStoredDays = "No stored days",
            daysFraction = { present, total -> "$present/$total days" },
            tempDisplay = { temp -> "Temp: ${temp}\u00B0C" },
            missingDaysMessage = { month, year, missing -> "$month $year is missing $missing day(s). Download missing data?" },
            notDownloadedMessage = { month, year -> "$month $year is not yet downloaded. Download now?" },

            // Month Names - Short
            monthShortJan = "Jan",
            monthShortFeb = "Feb",
            monthShortMar = "Mar",
            monthShortApr = "Apr",
            monthShortMay = "May",
            monthShortJun = "Jun",
            monthShortJul = "Jul",
            monthShortAug = "Aug",
            monthShortSep = "Sep",
            monthShortOct = "Oct",
            monthShortNov = "Nov",
            monthShortDec = "Dec",

            // Month Names - Full
            monthJanuary = "January",
            monthFebruary = "February",
            monthMarch = "March",
            monthApril = "April",
            monthMay = "May",
            monthJune = "June",
            monthJuly = "July",
            monthAugust = "August",
            monthSeptember = "September",
            monthOctober = "October",
            monthNovember = "November",
            monthDecember = "December",

            // MonthlyStatisticsView
            monthlySummary = "Monthly Summary",
            daysOfInterest = { count -> "Days of Interest: $count" },
            generalStats = "General Stats",
            dailyBreakdown = "Daily Breakdown",
            daysWithData = { count -> "Days with data: $count" },
            avgMinTemp = { temp -> "Average Min Temp: $temp" },
            avgMaxTemp = { temp -> "Average Max Temp: $temp" },
            overallAvgTemp = { temp -> "Overall Average Temp: $temp" },
            coldestDay = { temp, date -> "Coldest: $temp (on $date)" },
            hottestDay = { temp, date -> "Warmest: $temp (on $date)" },
            totalSolarEnergy = { energy -> "Total Solar Energy: $energy kWh/m\u00B2" },
            totalRainfall = { mm -> "Total Rainfall: $mm mm" },
            noWeatherData = "No detailed weather data available for calculations in this month, or data is still loading.",
            downloadMissingDays = { count -> if (count == 1) "Download $count missing day" else "Download $count missing days" },
            daysRecorded = { count -> if (count == 1) "$count day recorded" else "$count days recorded" },
            statTempLabel = "Temps",
            statTempValue = { min, max -> "$min–$max" },
            statWindLabel = "Avg Wind",
            statRainfallLabel = "Rainfall",
            statKiteableDaysLabel = "Kiteable Days",
            unitCelsius = "°C",
            unitKmh = " km/h",
            unitMm = " mm",
            unitDays = " days",
            dailyWind = "Daily Wind",

            // WeatherCards
            maxTemp = "Max Temp",
            avgTemp = "Avg Temp",
            minTemp = "Min Temp",
            avgWind = "Avg Wind",
            sustWind = "Sust. Wind",
            maxWind = "Max Wind",
            noDate = "No date",

            // DaySummaryRow
            dayWindBestWindowLabel = "best 2h avg",
            noDetails = "No details",
            solarEnergy = { value -> "Solar Energy: $value" },
            lowVisibilityDesc = "Low Visibility",
            lowVisibilityHours = { hours -> "Low visibility for $hours hour(s)" },
            collapse = "Collapse",
            expand = "Expand",
            dayMinTemp = { temp -> "Min: $temp\u00B0C" },
            dayMaxTemp = { temp -> "Max: $temp\u00B0C" },
            dayWindDirection = { dir -> "Wind direction: $dir" },
            dayRainfall = { mm -> "Rainfall: $mm mm" },
            daySunrise = { time -> "Sunrise: $time" },
            daySunset = { time -> "Sunset: $time" },
            hourlyWindSpeedLegend = "Wind speed",
            hourlyWindGustLegend = "Gusts",
            hourlySustainedWindowLegend = "Sustained window",
            hourlyMeetsThresholdLegend = "Meets threshold",
            noHourlyData = "No hourly data available for this day",
            hourlyWindChartDesc = { date, minSpeed, maxSpeed, maxGust ->
                "Hourly wind chart for $date. Speed range $minSpeed–$maxSpeed km/h, gusts up to $maxGust km/h."
            },
            windDirectionDesc = { compass -> "Wind direction: $compass" },

            // CalendarSelectors
            selectYear = "Select Year:",
            selectMonth = "Select Month:",
            noDataAvailable = "No data available.",
            monthFallbackNa = "N/A",
            monthFallbackNumber = { num -> "Month $num" },

            // Days of Interest
            daysOfInterestTitle = "Days of Interest",
            daysOfInterestDescription = "Describe your ideal day in natural language. AI will parse your criteria.",
            daysOfInterestPlaceholder = "e.g. sustained wind 12+ knots from SW, temperature above 5\u00B0C",
            daysOfInterestCurrent = { criteria -> "Current: $criteria" },
            daysOfInterestParsing = "Parsing criteria with AI...",
            daysOfInterestSave = "Set Filter",
            daysOfInterestError = { msg -> "Could not parse: $msg" }
        )

        val German = AppStrings(
            // Common / Shared
            ok = "OK",
            cancel = "Abbrechen",
            done = "Fertig",
            delete = "L\u00F6schen",
            back = "Zur\u00FCck",
            save = "Speichern",
            downloading = "Herunterladen...",
            previousMonth = "Voriger Monat",
            nextMonth = "Nächster Monat",
            appTitle = "ReWinds",
            dismiss = "Schlie\u00DFen",
            download = "Herunterladen",

            // HomeView
            savedLocations = "Gespeicherte Orte",
            searchPlaceholder = "Neue Orte suchen...",
            apiError = "API-Fehler",
            deletePlaceTitle = "Ort l\u00F6schen",
            deletePlaceMessage = { name -> "M\u00F6chten Sie '$name' wirklich l\u00F6schen? Diese Aktion kann nicht r\u00FCckg\u00E4ngig gemacht werden." },
            settingsIconDesc = "Einstellungen",
            chatIconDesc = "KI-Chat",
            daysStored = { count -> if (count == 1) "$count Tag gespeichert" else "$count Tage gespeichert" },
            vcKeyNudgeTitle = "Wetterdaten nicht eingerichtet",
            vcKeyNudgeBody = "ReWinds nutzt Visual Crossing als Wetterdatenquelle. Fügen Sie Ihren API-Schlüssel hinzu, um Wetterdaten herunterladen zu können.",
            vcKeyNudgeAction = "Jetzt einrichten",
            claudeKeyNudgeTitle = "KI-Chat nicht eingerichtet",
            claudeKeyNudgeBody = "Der KI-Chat nutzt Claude von Anthropic. Fügen Sie Ihren Anthropic-API-Schlüssel hinzu, um zu chatten.",
            claudeKeyNudgeAction = "Jetzt einrichten",

            // ChatView
            chatTitle = "Chat",
            messagePlaceholder = "Nachricht eingeben...",
            sendMessageDesc = "Nachricht senden",
            sessionSwitcherIconDesc = "Chatverlauf",
            sessionSwitcherTitle = "Ihre Chats",
            sessionSwitcherNewChat = "Neuer Chat",
            sessionSwitcherEmpty = "Noch keine gespeicherten Chats. Starten Sie einen neuen.",
            sessionSwitcherClose = "Chatliste schließen",
            sessionSwitcherActiveDesc = "Aktueller Chat",
            sessionMessageCount = { count -> if (count == 1L) "$count Nachricht" else "$count Nachrichten" },
            apiKeyNotConfigured = "API-Schl\u00FCssel nicht konfiguriert",
            apiKeyNotConfiguredMessage = "Um den KI-Chat zu nutzen, f\u00FCgen Sie Ihren Anthropic-API-Schl\u00FCssel in den Einstellungen hinzu. Einen Schl\u00FCssel erhalten Sie in der Anthropic-Konsole.",
            warningIconDesc = "Warnung",
            goToSettings = "Zu Einstellungen",
            claudeKeyInvalidTitle = "Claude API-Schl\u00FCssel ung\u00FCltig",
            claudeKeyInvalidMessage = "Ihr Anthropic-API-Schl\u00FCssel wurde abgelehnt (401/403). Bitte \u00FCberpr\u00FCfen Sie Ihren Schl\u00FCssel in den Einstellungen.",
            vcKeyMissingTitle = "Wetter-API-Schl\u00FCssel nicht konfiguriert",
            vcKeyMissingMessage = "Ein Visual-Crossing-API-Schl\u00FCssel wird ben\u00F6tigt. F\u00FCgen Sie Ihren Schl\u00FCssel in den Einstellungen hinzu.",
            vcKeyInvalidTitle = "Wetter-API-Schl\u00FCssel ung\u00FCltig",
            vcKeyInvalidMessage = "Ihr Visual-Crossing-API-Schl\u00FCssel wurde abgelehnt (401/403). Bitte \u00FCberpr\u00FCfen Sie Ihren Schl\u00FCssel in den Einstellungen.",

            // SettingsView
            settingsTitle = "Einstellungen",
            languageTitle = "Sprache",
            anthropicKeyTitle = "Anthropic API-Schl\u00FCssel",
            anthropicKeyDescription = "Geben Sie Ihren Anthropic-API-Schl\u00FCssel ein, um den KI-Chat zu nutzen. Ihr Schl\u00FCssel wird sicher auf Ihrem Ger\u00E4t gespeichert.",
            apiKeyConfigured = "\u2713 API-Schl\u00FCssel ist konfiguriert",
            apiKeyNotConfiguredStatus = "\u26A0 API-Schl\u00FCssel nicht konfiguriert",
            apiKeySaved = "\u2713 API-Schl\u00FCssel gespeichert",
            apiKeyEmptyError = "Bitte geben Sie Ihren API-Schl\u00FCssel ein.",
            apiKeyPlaceholder = "sk-ant-...",
            apiKeyFieldLabel = "API-Schl\u00FCssel",
            anthropicApiUrl = "Noch keinen Schl\u00FCssel?",
            anthropicApiLinkLabel = "API-Schl\u00FCssel in der Anthropic-Konsole holen",
            saveKey = "Schl\u00FCssel speichern",
            visualCrossingKeyTitle = "Visual Crossing API-Schl\u00FCssel",
            visualCrossingKeyDescription = "Visual Crossing liefert die historischen Wetter- und Vorhersagedaten, die ReWinds antreiben. Sie k\u00F6nnen ein kostenloses Konto ohne Kreditkarte erstellen. Der kostenlose Tarif erlaubt 1.000 Datens\u00E4tze pro Tag, was f\u00FCr die private Nutzung reichlich ist. Ihr Schl\u00FCssel wird sicher lokal auf Ihrem Ger\u00E4t gespeichert.",
            visualCrossingApiUrl = "Erstellen Sie ein kostenloses Konto unter: https://www.visualcrossing.com/weather-api",
            deleteKeyTitle = { keyType -> "$keyType l\u00F6schen?" },
            deleteKeyMessage = { keyType -> "Dadurch wird Ihr gespeicherter $keyType entfernt. Sie k\u00F6nnen ihn sp\u00E4ter erneut \u00FCber die Einstellungen hinzuf\u00FCgen." },

            // SettingsView \u2014 grouped list (KIM-273)
            settingsGroupGeneral = "Allgemein",
            settingsGroupApiKeys = "API-Schl\u00FCssel",
            settingsGroupData = "Daten",
            settingsGroupAbout = "\u00DCber",
            settingsRowUnits = "Einheiten",
            settingsRowWindSpeed = "Windgeschwindigkeit",
            settingsRowAutoRefresh = "Automatisch aktualisieren",
            settingsRowWifiOnly = "Nur \u00FCber WLAN aktualisieren",
            settingsRowExportData = "Daten exportieren",
            settingsRowVersion = "Version",
            settingsRowDeleteAllData = "Alle Daten l\u00F6schen",
            settingsKeyConfiguredChip = "\u2713 Konfiguriert",
            settingsKeyNotSetChip = "Nicht festgelegt",
            settingsAnthropicSubLabel = "KI-Chat-Funktion",
            settingsVisualCrossingSubLabel = "Wetterdaten",
            settingsAppVersion = "1.0.0",
            settingsRowWhatIsReWinds = "Was ist ReWinds?",
            settingsRowSendFeedback = "Feedback senden",

            // Welcome / onboarding guide (KIM-334)
            welcomeTitle = "Willkommen bei ReWinds",
            welcomeWhatItIsHeading = "Wofür es da ist",
            welcomeWhatItIsBody = "ReWinds hilft Windsport-Begeisterten, gute Spots zu finden. Suche einen Ort und erkunde seine historischen Wind- und Wettermuster – Dauerwind, Böen und Monatsstatistiken – um Reisen zu planen und dem Wind zu folgen.",
            welcomeWhatItIsNotHeading = "Was es nicht ist",
            welcomeWhatItIsNotBody = "Es ist keine Live-Wettervorhersage-App. ReWinds sagt dir nicht das Wetter von morgen – es zeigt die historischen Muster, die verraten, wo und wann der Wind typischerweise weht.",
            welcomeGetStarted = "Los geht’s",
            welcomeDone = "Fertig",

            // Feedback email (KIM-334)
            feedbackEmailSubject = "ReWinds Feedback",
            feedbackEmailBodyIntro = "Sag uns, was du denkst:",

            // StationMapModal
            noStationData = "Keine Stationsdaten verfügbar",
            refreshStations = "Stationen aktualisieren",
            refreshStationsDesc = "Wetterstationsdaten aktualisieren",
            unknownStation = "Unbekannte Station",
            stationRefreshError = { msg -> "Aktualisierung fehlgeschlagen: $msg" },
            closeMap = "Karte schließen",
            mapStationIconDesc = "Wetterstationen",
            mapSheetSubtitle = { count, km -> "$count Wetterstationen · nächste $km km" },
            mapSheetSubtitleNoDistance = { count -> "$count Wetterstationen" },
            stationsNearby = { count -> "$count Wetterstationen in der Nähe" },
            closestStationAway = { km -> "Nächste Station $km km entfernt" },
            noStationsNearby = "Keine Wetterstationen in der Nähe",

            // PlaceSummaryView
            infoIconDesc = "Info",
            openMapButton = "Stationskarte öffnen",
            chatButton = "Chat",
            monthPartialLabel = "Teilweise",
            monthDownloadedLabel = "Heruntergeladen",
            downloadFullMonth = "Ganzen Monat herunterladen?",
            loadingSummary = "Wetterzusammenfassung wird geladen...",
            errorLabel = "Fehler:",
            noStoredDays = "Keine gespeicherten Tage",
            daysFraction = { present, total -> "$present/$total Tage" },
            tempDisplay = { temp -> "Temp: ${temp}\u00B0C" },
            missingDaysMessage = { month, year, missing -> "$month $year fehlt $missing Tag(e). Fehlende Daten herunterladen?" },
            notDownloadedMessage = { month, year -> "$month $year wurde noch nicht heruntergeladen. Jetzt herunterladen?" },

            // Month Names - Short
            monthShortJan = "Jan",
            monthShortFeb = "Feb",
            monthShortMar = "M\u00E4r",
            monthShortApr = "Apr",
            monthShortMay = "Mai",
            monthShortJun = "Jun",
            monthShortJul = "Jul",
            monthShortAug = "Aug",
            monthShortSep = "Sep",
            monthShortOct = "Okt",
            monthShortNov = "Nov",
            monthShortDec = "Dez",

            // Month Names - Full
            monthJanuary = "Januar",
            monthFebruary = "Februar",
            monthMarch = "M\u00E4rz",
            monthApril = "April",
            monthMay = "Mai",
            monthJune = "Juni",
            monthJuly = "Juli",
            monthAugust = "August",
            monthSeptember = "September",
            monthOctober = "Oktober",
            monthNovember = "November",
            monthDecember = "Dezember",

            // MonthlyStatisticsView
            monthlySummary = "Monatliche Zusammenfassung",
            daysOfInterest = { count -> "Interessante Tage: $count" },
            generalStats = "Allgemeine Statistiken",
            dailyBreakdown = "Tages\u00FCbersicht",
            daysWithData = { count -> "Tage mit Daten: $count" },
            avgMinTemp = { temp -> "Durchschn. Mindesttemperatur: $temp" },
            avgMaxTemp = { temp -> "Durchschn. H\u00F6chsttemperatur: $temp" },
            overallAvgTemp = { temp -> "Gesamtdurchschnittstemperatur: $temp" },
            coldestDay = { temp, date -> "K\u00E4ltester Tag: $temp (am $date)" },
            hottestDay = { temp, date -> "W\u00E4rmster Tag: $temp (am $date)" },
            totalSolarEnergy = { energy -> "Gesamte Sonnenenergie: $energy kWh/m\u00B2" },
            totalRainfall = { mm -> "Gesamtniederschlag: $mm mm" },
            noWeatherData = "Keine detaillierten Wetterdaten f\u00FCr Berechnungen in diesem Monat verf\u00FCgbar, oder die Daten werden noch geladen.",
            downloadMissingDays = { count -> if (count == 1) "$count fehlenden Tag herunterladen" else "$count fehlende Tage herunterladen" },
            daysRecorded = { count -> if (count == 1) "$count Tag erfasst" else "$count Tage erfasst" },
            statTempLabel = "Temp",
            statTempValue = { min, max -> "$min\u2013$max" },
            statWindLabel = "Durchschn. Wind",
            statRainfallLabel = "Niederschlag",
            statKiteableDaysLabel = "Kite-Tage",
            unitCelsius = "\u00B0C",
            unitKmh = " km/h",
            unitMm = " mm",
            unitDays = " Tage",
            dailyWind = "T\u00E4glicher Wind",

            // WeatherCards
            maxTemp = "Max Temp",
            avgTemp = "Durchschn. Temp",
            minTemp = "Min Temp",
            avgWind = "Durchschn. Wind",
            sustWind = "Anhalte. Wind",
            maxWind = "Max Wind",
            noDate = "Kein Datum",

            // DaySummaryRow
            dayWindBestWindowLabel = "bester 2-Std.-Ø",
            noDetails = "Keine Details",
            solarEnergy = { value -> "Sonnenenergie: $value" },
            lowVisibilityDesc = "Geringe Sichtweite",
            lowVisibilityHours = { hours -> "Geringe Sichtweite f\u00FCr $hours Stunde(n)" },
            collapse = "Zuklappen",
            expand = "Ausklappen",
            dayMinTemp = { temp -> "Min: $temp\u00B0C" },
            dayMaxTemp = { temp -> "Max: $temp\u00B0C" },
            dayWindDirection = { dir -> "Windrichtung: $dir" },
            dayRainfall = { mm -> "Niederschlag: $mm mm" },
            daySunrise = { time -> "Sonnenaufgang: $time" },
            daySunset = { time -> "Sonnenuntergang: $time" },
            hourlyWindSpeedLegend = "Windgeschwindigkeit",
            hourlyWindGustLegend = "Böen",
            hourlySustainedWindowLegend = "Konstantes Fenster",
            hourlyMeetsThresholdLegend = "Erreicht Schwelle",
            noHourlyData = "Keine stündlichen Daten für diesen Tag verfügbar",
            hourlyWindChartDesc = { date, minSpeed, maxSpeed, maxGust ->
                "Stündliches Winddiagramm für $date. Geschwindigkeitsbereich $minSpeed–$maxSpeed km/h, Böen bis $maxGust km/h."
            },
            windDirectionDesc = { compass -> "Windrichtung: $compass" },

            // CalendarSelectors
            selectYear = "Jahr ausw\u00E4hlen:",
            selectMonth = "Monat ausw\u00E4hlen:",
            noDataAvailable = "Keine Daten verf\u00FCgbar.",
            monthFallbackNa = "N/V",
            monthFallbackNumber = { num -> "Monat $num" },

            // Days of Interest
            daysOfInterestTitle = "Interessante Tage",
            daysOfInterestDescription = "Beschreiben Sie Ihren idealen Tag in nat\u00FCrlicher Sprache. Die KI analysiert Ihre Kriterien.",
            daysOfInterestPlaceholder = "z.B. anhaltender Wind 12+ Knoten aus SW, Temperatur \u00FCber 5\u00B0C",
            daysOfInterestCurrent = { criteria -> "Aktuell: $criteria" },
            daysOfInterestParsing = "Kriterien werden mit KI analysiert...",
            daysOfInterestSave = "Filter setzen",
            daysOfInterestError = { msg -> "Konnte nicht analysiert werden: $msg" }
        )
    }
}
